-- Generated by SQLAlchemy

CREATE TABLE plans (
    id INTEGER NOT NULL AUTO_INCREMENT,
    name VARCHAR(50) NOT NULL,
    price FLOAT NOT NULL,
    quality VARCHAR(50) NOT NULL,
    PRIMARY KEY (id),
    UNIQUE (name)
);

CREATE TABLE users (
    id INTEGER NOT NULL AUTO_INCREMENT,
    email VARCHAR(120) NOT NULL,
    password_hash VARCHAR(128) NOT NULL,
    role VARCHAR(20) NOT NULL DEFAULT 'user',
    creation_date DATETIME NOT NULL,
    PRIMARY KEY (id),
    UNIQUE (email)
);

CREATE TABLE movies (
    id INTEGER NOT NULL AUTO_INCREMENT,
    title VARCHAR(150) NOT NULL,
    description TEXT,
    release_year INTEGER,
    genre VARCHAR(100),
    poster_url VARCHAR(255),
    PRIMARY KEY (id)
);

CREATE TABLE profiles (
    id INTEGER NOT NULL AUTO_INCREMENT,
    user_id INTEGER NOT NULL,
    name VARCHAR(50) NOT NULL,
    avatar_url VARCHAR(255),
    PRIMARY KEY (id),
    FOREIGN KEY(user_id) REFERENCES users (id)
);

CREATE TABLE subscriptions (
    id INTEGER NOT NULL AUTO_INCREMENT,
    user_id INTEGER NOT NULL,
    plan_id INTEGER NOT NULL,
    start_date DATETIME NOT NULL,
    end_date DATETIME,
    status VARCHAR(20) NOT NULL,
    PRIMARY KEY (id),
    FOREIGN KEY(user_id) REFERENCES users (id),
    FOREIGN KEY(plan_id) REFERENCES plans (id)
);

CREATE TABLE payments (
    id INTEGER NOT NULL AUTO_INCREMENT,
    subscription_id INTEGER NOT NULL,
    payment_date DATETIME NOT NULL,
    amount FLOAT NOT NULL,
    status VARCHAR(20) NOT NULL,
    PRIMARY KEY (id),
    FOREIGN KEY(subscription_id) REFERENCES subscriptions (id)
);

CREATE TABLE viewing_history (
    id INTEGER NOT NULL AUTO_INCREMENT,
    profile_id INTEGER NOT NULL,
    movie_id INTEGER NOT NULL,
    viewed_on DATETIME NOT NULL,
    PRIMARY KEY (id),
    FOREIGN KEY(profile_id) REFERENCES profiles (id),
    FOREIGN KEY(movie_id) REFERENCES movies (id)
);